// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cobratree

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"
)

// TestSplitShellArgs pins the whitespace + double-quote splitting used by
// the args-field passthrough. Behavior we rely on: bare whitespace splits,
// tabs split, double-quoted spans stay together, empty input yields nil.
func TestSplitShellArgs(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want []string
	}{
		{"empty", "", nil},
		{"single token", "contacts", []string{"contacts"}},
		{"two tokens", "inbox health", []string{"inbox", "health"}},
		{"extra whitespace", "  foo   bar  ", []string{"foo", "bar"}},
		{"tabs", "foo\tbar", []string{"foo", "bar"}},
		{"quoted token", `"hello world"`, []string{"hello world"}},
		{"mixed quoted and bare", `contacts "john doe" active`, []string{"contacts", "john doe", "active"}},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			got := SplitShellArgs(tc.in)
			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("splitShellArgs(%q) = %v, want %v", tc.in, got, tc.want)
			}
		})
	}
}

// TestCliArgsFromMCP_BlocksRootFlags pins the structured-parameter half of
// the control-plane-injection guard: even when an MCP client wraps the
// flag in the structured args map (instead of the free-form "args"
// string), the root flags listed in blockedRootFlags must be dropped
// before they reach exec.CommandContext. A regression here would let a
// caller redirect --base-url, swap --token, switch --client filesystems, or
// load a malicious --config.
func TestCliArgsFromMCP_BlocksRootFlags(t *testing.T) {
	in := map[string]any{
		"args":     "contacts",
		"base-url": "https://evil.example.com",
		"client":   "attacker-client",
		"config":   "/tmp/evil.yaml",
		"deliver":  "fd:3",
		"profile":  "attacker",
		"token":    "stolen-token",
		// Allowed per-command flag passes through.
		"limit": float64(10),
	}
	got := cliArgsFromMCP(in)
	want := []string{"--limit=10"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("cliArgsFromMCP dropped/kept wrong keys: got %v, want %v", got, want)
	}
	for _, blocked := range []string{"--base-url", "--client", "--config", "--deliver", "--profile", "--token", "--args"} {
		for _, tok := range got {
			if tok == blocked {
				t.Errorf("blocked flag %q leaked through cliArgsFromMCP", blocked)
			}
		}
	}
}

// TestCliArgsFromMCP_AllowsPerCommandFlags is the don't-overcorrect half:
// any flag NOT in blockedRootFlags must still pass through, including
// strings, bools, numbers, and []any. Without this, a tightening change
// to the blocklist that accidentally drops legitimate per-command flags
// would silently break every MCP-driven command. cliArgsFromMCP also
// guarantees sorted-key output (so generated commands see deterministic
// argv ordering); compare directly to catch a regression in either the
// blocklist or the sort.
func TestCliArgsFromMCP_AllowsPerCommandFlags(t *testing.T) {
	in := map[string]any{
		"query":   "alpha",
		"verbose": true,
		"limit":   float64(25),
		"tags":    []any{"a", "b"},
	}
	got := cliArgsFromMCP(in)
	want := []string{"--limit=25", "--query=alpha", "--tags=a,b", "--verbose"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("cliArgsFromMCP per-command passthrough: got %v, want %v", got, want)
	}
}

// TestCliArgsFromMCP_ValueCannotBecomeAFlag is the value-channel half of the
// control-plane-injection guard. blockedRootFlags filters argument NAMES, so
// it cannot see a blocked flag smuggled in as an argument VALUE. Emitting
// "--k" and "v" as two tokens made that smuggling work: pflag does not
// consume a following token for a boolean flag, so the value token was
// re-parsed as a flag of its own and {"json": "--deliver=..."} set --deliver.
// Binding every value into the same token as its name ("--k=v") is what
// closes it; each case below is a payload that reached a blocked flag under
// the two-token form.
func TestCliArgsFromMCP_ValueCannotBecomeAFlag(t *testing.T) {
	payloads := []struct {
		name string
		in   map[string]any
	}{
		{"bool carrier", map[string]any{"json": "--deliver=webhook:https://attacker.example"}},
		{"bool carrier bare flag", map[string]any{"json": "--insecure"}},
		{"string carrier", map[string]any{"query": "--deliver=webhook:https://attacker.example"}},
		{"number carrier", map[string]any{"limit": "--token=stolen"}},
		{"array carrier", map[string]any{"tags": []any{"--config=/tmp/evil.yaml"}}},
	}
	for _, p := range payloads {
		t.Run(p.name, func(t *testing.T) {
			for _, tok := range cliArgsFromMCP(p.in) {
				// Every emitted token must be exactly one "--name=value" (or a
				// bare "--name" for a true bool). A token that is only the
				// payload means the value escaped into flag position.
				if !strings.HasPrefix(tok, "--") {
					t.Fatalf("emitted a non-flag token %q; a value escaped into flag position", tok)
				}
				name := strings.TrimPrefix(tok, "--")
				if i := strings.Index(name, "="); i >= 0 {
					name = name[:i]
				}
				if blockedRootFlags[name] {
					t.Fatalf("token %q carries blocked flag %q in flag position", tok, name)
				}
			}
		})
	}
}

// TestCliArgsFromMCP_RejectsUnsafeFlagNames covers the other end of the same
// boundary: an argument NAME containing "=" or leading with "-" stops being a
// name once "--" is prepended, which would let a caller relocate the
// name/value split that blockedRootFlags depends on.
func TestCliArgsFromMCP_RejectsUnsafeFlagNames(t *testing.T) {
	in := map[string]any{
		"json=true --deliver": "webhook:https://attacker.example",
		"-deliver":            "webhook:https://attacker.example",
		"":                    "empty",
		"limit":               float64(5),
	}
	got := cliArgsFromMCP(in)
	want := []string{"--limit=5"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("cliArgsFromMCP kept an unsafe flag name: got %v, want %v", got, want)
	}
}

// TestArgsFieldRejectsFlagLikeTokens covers the free-form "args" string
// half of the control-plane-injection guard. shellOutToCLI is a closure
// that requires a real binary on PATH; we exercise the same guard logic
// here so a regression that drops the strings.HasPrefix("-") check is
// caught at unit-test scope rather than only via end-to-end MCP runs.
func TestArgsFieldRejectsFlagLikeTokens(t *testing.T) {
	guard := func(raw string) (rejected string, ok bool) {
		for _, t := range SplitShellArgs(raw) {
			if strings.HasPrefix(t, "-") {
				return t, false
			}
		}
		return "", true
	}
	cases := []struct {
		name        string
		in          string
		wantOK      bool
		wantBlocked string
	}{
		{"long flag", "--config /tmp/evil.yaml", false, "--config"},
		{"short flag", "-c", false, "-c"},
		{"bare double dash", "--", false, "--"},
		{"flag with equals", "--config=/tmp/evil.yaml", false, "--config=/tmp/evil.yaml"},
		{"flag mid-args", "contacts --verbose", false, "--verbose"},
		{"clean positional", "contacts", true, ""},
		{"two positionals", "inbox health", true, ""},
		{"empty", "", true, ""},
		// Shell metachars in unquoted positional content stay verbatim;
		// the CLI is invoked via exec.CommandContext (no /bin/sh), so
		// $VAR / && / | are inert. Pin that they don't trip the guard.
		{"shell metachars in positional", `name with $VAR && pipe|stuff`, true, ""},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			tok, ok := guard(tc.in)
			if ok != tc.wantOK {
				t.Errorf("guard(%q) ok = %v, want %v", tc.in, ok, tc.wantOK)
			}
			if !tc.wantOK && tok != tc.wantBlocked {
				t.Errorf("guard(%q) blocked = %q, want %q", tc.in, tok, tc.wantBlocked)
			}
		})
	}
}

func TestRunCLICommandKeepsStdoutSeparateFromStderr(t *testing.T) {
	bin := writeShelloutHelper(t, "success")
	got, err := RunCLICommand(context.Background(), bin, []string{"alpha", "beta"})
	if err != nil {
		t.Fatalf("RunCLICommand success returned error: %v", err)
	}
	if !strings.Contains(got, `{"args":"alpha beta"}`) {
		t.Fatalf("stdout result missing JSON payload: %q", got)
	}
	if strings.Contains(got, "telemetry") {
		t.Fatalf("stderr telemetry leaked into stdout: %q", got)
	}
}

func TestRunCLICommandReportsStderrOnFailure(t *testing.T) {
	bin := writeShelloutHelper(t, "fail-stderr")
	_, err := RunCLICommand(context.Background(), bin, nil)
	if err == nil {
		t.Fatal("RunCLICommand fail-stderr succeeded unexpectedly")
	}
	if !strings.Contains(err.Error(), "boom from stderr") {
		t.Fatalf("error did not include stderr: %v", err)
	}
}

func TestRunCLICommandFallsBackToStdoutOnFailureWithoutStderr(t *testing.T) {
	bin := writeShelloutHelper(t, "fail-stdout")
	_, err := RunCLICommand(context.Background(), bin, nil)
	if err == nil {
		t.Fatal("RunCLICommand fail-stdout succeeded unexpectedly")
	}
	if !strings.Contains(err.Error(), "stdout failure") {
		t.Fatalf("error did not include stdout fallback: %v", err)
	}
	if !strings.Contains(err.Error(), "output: stdout failure") {
		t.Fatalf("error did not label stdout fallback as output: %v", err)
	}
	if strings.Contains(err.Error(), "stderr: stdout failure") {
		t.Fatalf("stdout fallback mislabeled as stderr: %v", err)
	}
}

func writeShelloutHelper(t *testing.T, mode string) string {
	t.Helper()
	dir := t.TempDir()
	if runtime.GOOS == "windows" {
		path := filepath.Join(dir, "helper.bat")
		var body string
		switch mode {
		case "success":
			body = "@echo off\r\necho telemetry 1>&2\r\necho {\"args\":\"%*\"}\r\n"
		case "fail-stderr":
			body = "@echo off\r\necho boom from stderr 1>&2\r\nexit /b 7\r\n"
		case "fail-stdout":
			body = "@echo off\r\necho stdout failure\r\nexit /b 7\r\n"
		default:
			t.Fatalf("unknown mode %q", mode)
		}
		if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
			t.Fatalf("write helper: %v", err)
		}
		return path
	}
	path := filepath.Join(dir, "helper.sh")
	var body string
	switch mode {
	case "success":
		body = "#!/bin/sh\necho telemetry >&2\nprintf '{\"args\":\"%s\"}\\n' \"$*\"\n"
	case "fail-stderr":
		body = "#!/bin/sh\necho boom from stderr >&2\nexit 7\n"
	case "fail-stdout":
		body = "#!/bin/sh\necho stdout failure\nexit 7\n"
	default:
		t.Fatalf("unknown mode %q", mode)
	}
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		t.Fatalf("write helper: %v", err)
	}
	return path
}
