// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bufio"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"printing-press-oauth2-pp-cli/internal/cliutil"
	"printing-press-oauth2-pp-cli/internal/config"
)

func newAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "auth",
		Short: "Manage authentication for Printing Press Oauth2",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAuthSetupCmd(flags))
	cmd.AddCommand(newAuthLoginCmd(flags))
	cmd.AddCommand(newAuthStatusCmd(flags))
	cmd.AddCommand(newAuthLogoutCmd(flags))

	return cmd
}

// newAuthSetupCmd prints concrete steps for registering an OAuth app and
// obtaining client credentials. Side-effect rule: print by default, --launch
// to open the registration URL, short-circuit when the verifier is running.
func newAuthSetupCmd(_ *rootFlags) *cobra.Command {
	var launch bool
	cmd := &cobra.Command{
		Use:     "setup",
		Short:   "Print steps for registering an OAuth app (use --launch to open the URL)",
		Example: "  printing-press-oauth2-pp-cli auth setup\n  printing-press-oauth2-pp-cli auth setup --launch",
		RunE: func(cmd *cobra.Command, args []string) error {
			w := cmd.OutOrStdout()
			fmt.Fprintln(w, "No setup URL is configured for this CLI; check the API's docs.")
			fmt.Fprintln(w, "")
			fmt.Fprintln(w, "Then run:")
			fmt.Fprintln(w, "  printing-press-oauth2-pp-cli login")
			if !launch {
				return nil
			}
			fmt.Fprintln(cmd.ErrOrStderr(), "no setup URL configured; cannot launch")
			return nil
		},
	}
	cmd.Flags().BoolVar(&launch, "launch", false, "Open the setup URL in your default browser")
	return cmd
}

func newAuthLoginCmd(flags *rootFlags) *cobra.Command {
	var clientID string
	var clientSecret string
	var port int

	cmd := &cobra.Command{
		Use:   "login",
		Short: "Authenticate via OAuth2",
		Annotations: map[string]string{
			"mcp:hidden": "true",
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			return runOAuthLogin(cmd, flags, clientID, clientSecret, port)
		},
	}

	cmd.Flags().StringVar(&clientID, "client-id", os.Getenv("PRINTING_PRESS_OAUTH2_CLIENT_ID"), "OAuth2 client ID")
	cmd.Flags().StringVar(&clientSecret, "client-secret", os.Getenv("PRINTING_PRESS_OAUTH2_CLIENT_SECRET"), "OAuth2 client secret")
	cmd.Flags().IntVar(&port, "port", 8085, "Local callback server port")

	return cmd
}

func runOAuthLogin(cmd *cobra.Command, flags *rootFlags, clientID, clientSecret string, port int) error {
	w := cmd.OutOrStdout()
	cfg, err := config.Load(flags.configPath)
	if err != nil {
		return err
	}
	tokenURL := ""
	// Resolved up front, not after the callback: a rejected override is a
	// configuration error, and discovering it only after the user has opened a
	// browser and completed a login wastes the whole flow to report it.
	tokenURL, err = config.ResolveTokenURL(cfg.TokenURL)
	if err != nil {
		return authErr(err)
	}
	// Resolved before every return path, including the credential-free probe
	// below: a misconfigured redirect host is a configuration error whether or
	// not credentials happen to be present, and validating it only on the path
	// that reaches the browser would let a probe report success for a value
	// the real flow refuses.
	//
	// RFC 8252 §7.3 prescribes the loopback IP literal, and some providers do
	// reject "localhost" — but the reverse is also true, and the RFC does not
	// bind a provider's registration form: Intuit's developer portal refuses
	// 127.0.0.1 as a redirect URI outright, so a CLI that can only send the IP
	// literal cannot authorize against them at all. That failure is silent and
	// expensive to diagnose: the provider accepts the authorize request, the
	// user signs in and approves, and only then is the redirect refused, so
	// the callback server waits out its whole timeout for a request that was
	// never sent.
	//
	// Either spelling reaches the listener regardless of which is bound; a
	// client that resolves ::1 first falls back to 127.0.0.1.
	redirectHost := "127.0.0.1"
	if v := strings.TrimSpace(os.Getenv("PRINTING_PRESS_OAUTH2_OAUTH_REDIRECT_HOST")); v != "" {
		if err := validateRedirectHost(v); err != nil {
			return fmt.Errorf("invalid PRINTING_PRESS_OAUTH2_OAUTH_REDIRECT_HOST %q: %w", v, err)
		}
		redirectHost = strings.ToLower(v)
	}

	// Credential-free probes cannot construct an authorize URL. Keep supplied
	// or configured client IDs on the detailed verify path below so it still
	// emits PKCE params.
	if (dryRunOK(flags) || cliutil.IsVerifyEnv()) && clientID == "" && cfg.ClientID == "" {
		fmt.Fprintln(w, `{"status":"dry_run","action":"auth login","would":"start OAuth2 authorization-code flow (PKCE without client secret), open browser, capture loopback callback"}`)
		return nil
	}
	clientID, clientSecret, err = resolveOAuthCredentials(cmd, flags, cfg, clientID, clientSecret)
	if err != nil {
		return err
	}

	stateBytes := make([]byte, 16)
	if _, err := rand.Read(stateBytes); err != nil {
		return fmt.Errorf("generating state: %w", err)
	}
	state := hex.EncodeToString(stateBytes)

	// RFC 7636 PKCE: with no client secret this is a public client, and a
	// bare authorization_code grant reaches the token endpoint with no
	// client authentication at all — providers reject that. When a secret
	// is configured, keep the plain Authorization Code flow unchanged.
	codeVerifier := ""
	if clientSecret == "" {
		codeVerifier, err = generatePKCEVerifier()
		if err != nil {
			return err
		}
	}

	authURL := ""
	authURL = cfg.AuthorizationURL
	if authURL == "" {
		authURL = "https://accounts.authcode.example/oauth/authorize"
	}
	params := url.Values{
		"client_id":     {clientID},
		"response_type": {"code"},
		"state":         {state},
	}
	if codeVerifier != "" {
		params.Set("code_challenge", pkceCodeChallengeS256(codeVerifier))
		params.Set("code_challenge_method", "S256")
	}
	scopes := []string{"read", "write"}
	if len(scopes) > 0 {
		params.Set("scope", strings.Join(scopes, " "))
	}

	// Short-circuit BEFORE binding the callback port or opening a browser, so
	// verify / validate-narrative neither binds the loopback port (which would
	// EADDRINUSE on a parallel run or occupied port) nor launches a browser
	// (which would time out). The redirect_uri shown here is informational and
	// derived from the configured --port; the live flow below uses the actual
	// bound port, which the OS assigns when --port 0 is passed.
	if cliutil.IsVerifyEnv() {
		params.Set("redirect_uri", fmt.Sprintf("http://%s:%d/callback", redirectHost, port))
		fmt.Fprintf(w, "would launch: %s\n", authURL+"?"+params.Encode())
		return nil
	}

	// Resolved before any side effect: past this point the flow binds a port,
	// opens the user's browser, and starts a server, so a malformed override
	// discovered later would cost a browser tab and a dangling listener to
	// report a plain configuration error.
	//
	// A real browser login is sign-in, then possibly MFA, then picking which
	// company/workspace to connect, then reading a consent screen. Two minutes
	// routinely lost that race, and losing it is expensive: the callback
	// server is gone by the time the user approves, so the authorization lands
	// on a dead port and the whole flow restarts. Wait long enough that only a
	// genuinely abandoned login times out.
	authTimeout := 15 * time.Minute
	if v := strings.TrimSpace(os.Getenv("PRINTING_PRESS_OAUTH2_AUTH_TIMEOUT")); v != "" {
		parsed, err := time.ParseDuration(v)
		if err != nil {
			return fmt.Errorf("invalid PRINTING_PRESS_OAUTH2_AUTH_TIMEOUT %q: %w", v, err)
		}
		if parsed <= 0 {
			return fmt.Errorf("PRINTING_PRESS_OAUTH2_AUTH_TIMEOUT must be positive, got %q", v)
		}
		authTimeout = parsed
	}

	listener, err := net.Listen("tcp", fmt.Sprintf("127.0.0.1:%d", port))
	if err != nil {
		return fmt.Errorf("starting callback server: %w", err)
	}
	defer listener.Close()

	// Derive the redirect URI from the live listener address so an OS-assigned
	// ephemeral port (--port 0) is reflected in both the auth request and the
	// token exchange below. redirectHost was resolved above the verify
	// short-circuit so both paths name the same host.
	redirectURI := fmt.Sprintf("http://%s:%d/callback", redirectHost, listener.Addr().(*net.TCPAddr).Port)
	params.Set("redirect_uri", redirectURI)
	fullURL := authURL + "?" + params.Encode()

	fmt.Fprintf(os.Stderr, "Opening browser for authentication...\n")
	fmt.Fprintf(os.Stderr, "If the browser doesn't open, visit:\n%s\n\n", fullURL)
	openBrowser(fullURL)

	codeCh := make(chan string, 1)
	errCh := make(chan error, 1)

	mux := http.NewServeMux()
	mux.HandleFunc("/callback", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Query().Get("state") != state {
			errCh <- fmt.Errorf("state mismatch")
			http.Error(w, "State mismatch", http.StatusBadRequest)
			return
		}
		if errMsg := r.URL.Query().Get("error"); errMsg != "" {
			errCh <- fmt.Errorf("auth error: %s", errMsg)
			http.Error(w, errMsg, http.StatusBadRequest)
			return
		}
		code := r.URL.Query().Get("code")
		if code == "" {
			errCh <- fmt.Errorf("no code in callback")
			http.Error(w, "No code", http.StatusBadRequest)
			return
		}
		w.Header().Set("Content-Type", "text/html")
		fmt.Fprint(w, "<html><body><h2>Authentication successful!</h2><p>You can close this tab.</p></body></html>")
		codeCh <- code
	})

	server := &http.Server{Handler: mux}
	go server.Serve(listener)

	var code string
	select {
	case code = <-codeCh:
	case err := <-errCh:
		return err
	case <-time.After(authTimeout):
		return fmt.Errorf("authentication timed out after %s; set PRINTING_PRESS_OAUTH2_AUTH_TIMEOUT to allow longer", authTimeout)
	}

	server.Shutdown(context.Background())

	tokenParams := url.Values{
		"grant_type":   {"authorization_code"},
		"code":         {code},
		"redirect_uri": {redirectURI},
		"client_id":    {clientID},
	}
	if clientSecret != "" {
		tokenParams.Set("client_secret", clientSecret)
	} else {
		tokenParams.Set("code_verifier", codeVerifier)
	}

	// The browser-wait timeout above does not apply here; the token exchange
	// is a plain server-to-server POST and gets its own short network timeout,
	// while cmd.Context() keeps it cancellable from the terminal.
	tokenReq, err := http.NewRequestWithContext(cmd.Context(), http.MethodPost, tokenURL, strings.NewReader(tokenParams.Encode()))
	if err != nil {
		return fmt.Errorf("building token request: %w", err)
	}
	tokenReq.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	tokenClient := &http.Client{Timeout: 30 * time.Second}
	resp, err := tokenClient.Do(tokenReq)
	if err != nil {
		return fmt.Errorf("exchanging code for token: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		var body map[string]any
		if err := json.NewDecoder(resp.Body).Decode(&body); err == nil {
			return fmt.Errorf("exchanging code for token: HTTP %d: %v", resp.StatusCode, body)
		}
		return fmt.Errorf("exchanging code for token: HTTP %d", resp.StatusCode)
	}

	var tokenResp struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
		ExpiresIn    int    `json:"expires_in"`
		TokenType    string `json:"token_type"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&tokenResp); err != nil {
		return fmt.Errorf("parsing token response: %w", err)
	}
	if tokenResp.AccessToken == "" {
		return fmt.Errorf("no access token in response")
	}

	// Guard against non-conformant servers that return expires_in: 0.
	// A zero-duration expiry resolves to time.Now(), which authHeader()
	// then treats as expired and triggers a refresh on every call.
	expiry := time.Time{}
	if tokenResp.ExpiresIn > 0 {
		expiry = time.Now().Add(time.Duration(tokenResp.ExpiresIn) * time.Second)
	}
	if err := cfg.SaveTokens(clientID, clientSecret, tokenResp.AccessToken, tokenResp.RefreshToken, expiry); err != nil {
		return fmt.Errorf("saving tokens: %w", err)
	}

	if expiry.IsZero() {
		fmt.Fprintf(os.Stderr, "%s Authentication successful! Token expiry not provided.\n", green("OK"))
	} else {
		fmt.Fprintf(os.Stderr, "%s Authentication successful! Token expires at %s\n", green("OK"), expiry.Format(time.RFC3339))
	}
	return nil
}

func resolveOAuthCredentials(cmd *cobra.Command, flags *rootFlags, cfg *config.Config, clientID, clientSecret string) (string, string, error) {
	explicitClientID := clientID
	if clientID == "" && cfg != nil {
		clientID = cfg.ClientID
	}
	if clientSecret == "" && cfg != nil && (explicitClientID == "" || explicitClientID == cfg.ClientID) {
		clientSecret = cfg.ClientSecret
	}
	if clientID != "" {
		return clientID, clientSecret, nil
	}
	if flags.noInput {
		return "", "", fmt.Errorf("OAuth2 client ID is required; pass --client-id, set PRINTING_PRESS_OAUTH2_CLIENT_ID, or run 'printing-press-oauth2-pp-cli login' without --no-input")
	}
	reader := bufio.NewReader(cmd.InOrStdin())
	printOAuthCredentialHint(cmd.ErrOrStderr())
	clientID, err := promptOAuthCredential(cmd, reader, "OAuth2 Client ID")
	if err != nil {
		return "", "", err
	}
	if clientID == "" {
		return "", "", fmt.Errorf("OAuth2 client ID is required")
	}
	if clientSecret == "" {
		clientSecret, err = promptOAuthCredential(cmd, reader, "OAuth2 Client Secret (press Enter if not required)")
		if err != nil {
			return "", "", err
		}
	}
	return clientID, clientSecret, nil
}

func printOAuthCredentialHint(w io.Writer) {
	fmt.Fprintln(w, "No setup URL is configured for this CLI; check the API's docs.")
}

func promptOAuthCredential(cmd *cobra.Command, reader *bufio.Reader, label string) (string, error) {
	fmt.Fprintf(cmd.ErrOrStderr(), "%s: ", label)
	line, err := reader.ReadString('\n')
	if err != nil && err != io.EOF {
		return "", fmt.Errorf("reading %s: %w", strings.ToLower(label), err)
	}
	return strings.TrimSpace(line), nil
}

func newAuthStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "status",
		Short: "Show authentication status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return err
			}

			w := cmd.OutOrStdout()
			authed := cfg.AccessToken != ""
			// JSON envelope: {authenticated, verified, source, config}.
			if flags.asJSON {
				out := map[string]any{
					"authenticated": authed,
					"verified":      false,
					"source":        cfg.AuthSource,
					"config":        cfg.Path,
				}
				return printJSONFiltered(w, out, flags)
			}

			if !authed {
				fmt.Fprintf(w, "  %s Not authenticated. Run 'printing-press-oauth2-pp-cli login' to authenticate.\n", red("FAIL"))
				return nil
			}

			if cfg.TokenExpiry.IsZero() {
				fmt.Fprintf(w, "  %s Credentials present (not verified; no expiry info)\n", green("OK"))
			} else if time.Now().Before(cfg.TokenExpiry) {
				fmt.Fprintf(w, "  %s Credentials present (not verified; expires %s)\n", green("OK"), cfg.TokenExpiry.Format(time.RFC3339))
			} else {
				if cfg.RefreshToken != "" {
					fmt.Fprintf(w, "  %s Token expired (will auto-refresh on next request)\n", yellow("WARN"))
				} else {
					fmt.Fprintf(w, "  %s Token expired. Run 'printing-press-oauth2-pp-cli login' to re-authenticate.\n", red("FAIL"))
				}
			}

			if cfg.AuthSource != "" {
				fmt.Fprintf(w, "  source: %s\n", cfg.AuthSource)
			}
			return nil
		},
	}
}

func newAuthLogoutCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "logout",
		Short: "Remove stored authentication tokens",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return err
			}
			if err := cfg.ClearTokens(); err != nil {
				return fmt.Errorf("clearing tokens: %w", err)
			}
			// JSON envelope: {cleared: true}. The OAuth flavor does not
			// surface a "note" key because env-var creds aren't part of
			// this auth flow's contract.
			if flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
					"cleared": true,
				}, flags)
			}
			fmt.Fprintf(os.Stderr, "Logged out. Tokens removed.\n")
			return nil
		},
	}
}

// generatePKCEVerifier returns a fresh RFC 7636 code verifier: 32 bytes of
// CSPRNG output, base64url-encoded without padding (43 chars, within the
// 43-128 range the RFC requires).
func generatePKCEVerifier() (string, error) {
	verifierBytes := make([]byte, 32)
	if _, err := rand.Read(verifierBytes); err != nil {
		return "", fmt.Errorf("generating PKCE verifier: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(verifierBytes), nil
}

// pkceCodeChallengeS256 derives the S256 code challenge for a verifier:
// base64url(SHA-256(verifier)) without padding.
func pkceCodeChallengeS256(verifier string) string {
	sum := sha256.Sum256([]byte(verifier))
	return base64.RawURLEncoding.EncodeToString(sum[:])
}

// validateRedirectHost keeps the redirect-host override pointed at this
// machine. The value is interpolated into the redirect_uri the provider sends
// the authorization code to, so a non-loopback host would hand that code to
// somewhere else — the classic redirect-hijack shape. The listener binds
// loopback regardless, so a remote host could never receive the callback
// anyway; rejecting it turns a silent hang into a clear error.
//
// Ports and schemes are not accepted: the port comes from the live listener
// and the scheme is fixed at http, which is what RFC 8252 §7.3 permits for a
// loopback redirect. A bare ::1 is likewise rejected — it needs bracketing to
// be a legal URL host, and no provider is known to want it when 127.0.0.1 and
// localhost both exist.
func validateRedirectHost(host string) error {
	if strings.ContainsAny(host, ":/@?#") {
		return fmt.Errorf("expected a bare host such as localhost or 127.0.0.1, not a URL, host:port, or IPv6 literal")
	}
	switch strings.ToLower(host) {
	case "localhost", "127.0.0.1":
		return nil
	}
	return fmt.Errorf("only loopback hosts are allowed (localhost, 127.0.0.1)")
}

func openBrowser(url string) {
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", url)
	case "linux":
		cmd = exec.Command("xdg-open", url)
	case "windows":
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", url)
	default:
		return
	}
	cmd.Start()
}
