package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/mvanhorn/cli-printing-press/v4/internal/graphql"
	"github.com/mvanhorn/cli-printing-press/v4/internal/openapi"
	"github.com/mvanhorn/cli-printing-press/v4/internal/pipeline"
	"github.com/mvanhorn/cli-printing-press/v4/internal/spec"
	"github.com/spf13/cobra"
)

func newToolsManifestCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tools-manifest",
		Short: "Manage tools-manifest.json metadata for printed CLIs",
		Long: `Manage the tools-manifest.json file that ships in every printed CLI's
root. tools-manifest.json describes every MCP tool the CLI exposes and is
consumed by ` + "`printing-press auth doctor`" + ` and ` + "`printing-press mcp-audit`" + `
without re-parsing the original spec.`,
	}
	cmd.AddCommand(newToolsManifestEmitCmd())
	return cmd
}

func newToolsManifestEmitCmd() *cobra.Command {
	var dir string
	var specPath string
	var asJSON bool
	var force bool

	cmd := &cobra.Command{
		Use:   "emit",
		Short: "Generate tools-manifest.json for a printed CLI from its spec",
		Long: `Generate (or regenerate) the tools-manifest.json file at the root of a
printed CLI directory. The file is derived from the CLI's stored spec
(spec.json by default) and the spec_format recorded in
.printing-press.json. Supported spec formats: openapi3, graphql, internal.

This is the recovery path for CLIs generated by older press versions
that didn't emit tools-manifest.json. Those CLIs are otherwise valid
but fail ` + "`printing-press publish validate`" + ` on the manifest check; running
emit unblocks them in place without re-running the full generate
pipeline. Idempotent: running it twice produces the same file unless
the source spec has changed.

When ` + "`--spec`" + ` is not supplied, the command looks for ` + "`spec.json`" + ` at the
CLI root. When ` + "`--force`" + ` is not supplied and tools-manifest.json already
exists, the command returns an error to avoid silently clobbering a
hand-edited file.`,
		Example: `  printing-press tools-manifest emit --dir ~/printing-press/library/google-ads
  printing-press tools-manifest emit --dir ./google-ads --force --json
  printing-press tools-manifest emit --dir ./notion --spec ./openapi.json`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if dir == "" {
				return &ExitError{Code: ExitInputError, Err: fmt.Errorf("--dir is required")}
			}
			absDir, err := filepath.Abs(dir)
			if err != nil {
				return fmt.Errorf("resolving --dir: %w", err)
			}
			info, statErr := os.Stat(absDir)
			if statErr != nil || !info.IsDir() {
				return &ExitError{Code: ExitInputError, Err: fmt.Errorf("%s is not a directory", absDir)}
			}

			manifest, err := pipeline.ReadCLIManifest(absDir)
			if err != nil {
				return &ExitError{
					Code: ExitInputError,
					Err:  fmt.Errorf("reading .printing-press.json (this directory may not be a printed CLI): %w", err),
				}
			}
			if manifest.SpecFormat == "" {
				return &ExitError{
					Code: ExitInputError,
					Err:  fmt.Errorf(".printing-press.json missing spec_format; cannot select a parser"),
				}
			}

			resolvedSpec := specPath
			if resolvedSpec == "" {
				resolvedSpec = filepath.Join(absDir, "spec.json")
			} else {
				resolvedSpec, err = filepath.Abs(resolvedSpec)
				if err != nil {
					return fmt.Errorf("resolving --spec: %w", err)
				}
			}
			if _, err := os.Stat(resolvedSpec); err != nil {
				return &ExitError{Code: ExitInputError, Err: fmt.Errorf("spec file not readable at %s: %w", resolvedSpec, err)}
			}

			outPath := filepath.Join(absDir, pipeline.ToolsManifestFilename)
			if !force {
				if info, err := os.Stat(outPath); err == nil && !info.IsDir() {
					return &ExitError{
						Code: ExitInputError,
						Err:  fmt.Errorf("%s already exists; pass --force to overwrite", pipeline.ToolsManifestFilename),
					}
				}
			}

			data, err := os.ReadFile(resolvedSpec)
			if err != nil {
				return fmt.Errorf("reading spec: %w", err)
			}

			var parsed *spec.APISpec
			switch manifest.SpecFormat {
			case "openapi3":
				parsed, err = openapi.ParseWithPath(data, resolvedSpec)
			case "graphql":
				parsed, err = graphql.ParseSDLBytes(resolvedSpec, data)
			case "internal":
				parsed, err = spec.ParseBytes(data)
			default:
				return &ExitError{
					Code: ExitInputError,
					Err:  fmt.Errorf("unsupported spec_format %q (want openapi3, graphql, or internal)", manifest.SpecFormat),
				}
			}
			if err != nil {
				return fmt.Errorf("parsing spec (%s): %w", manifest.SpecFormat, err)
			}

			if err := pipeline.WriteToolsManifest(absDir, parsed); err != nil {
				return fmt.Errorf("writing %s: %w", pipeline.ToolsManifestFilename, err)
			}

			if asJSON {
				out := map[string]any{
					"passed":      true,
					"dir":         absDir,
					"spec":        resolvedSpec,
					"spec_format": manifest.SpecFormat,
					"output":      outPath,
					"resources":   len(parsed.Resources),
				}
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(out)
			}

			fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", outPath)
			return nil
		},
	}

	cmd.Flags().StringVar(&dir, "dir", "", "CLI directory containing .printing-press.json and spec.json (required)")
	cmd.Flags().StringVar(&specPath, "spec", "", "Path to spec file (defaults to <dir>/spec.json)")
	cmd.Flags().BoolVar(&asJSON, "json", false, "Emit machine-readable JSON output")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite an existing tools-manifest.json")
	_ = cmd.MarkFlagRequired("dir")

	return cmd
}
