package cli

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/mvanhorn/cli-printing-press/v4/internal/graphql"
	"github.com/mvanhorn/cli-printing-press/v4/internal/openapi"
	"github.com/mvanhorn/cli-printing-press/v4/internal/pipeline"
	"github.com/mvanhorn/cli-printing-press/v4/internal/spec"
	"github.com/spf13/cobra"
)

// archivedSpecCandidates is the ordered list of filenames the press
// archives a generation spec under. Mirrors
// internal/pipeline/mcpsync/sync.go.loadArchivedSpec so this command
// works on every CLI mcpsync can already migrate.
var archivedSpecCandidates = []string{
	"spec.yaml",
	"spec.yml",
	"spec.json",
	"schema.graphql",
	"schema.gql",
}

func newToolsManifestCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tools-manifest",
		Short: "Manage tools-manifest.json metadata for printed CLIs",
		Long: `Manage the tools-manifest.json file that ships in every printed CLI's
root. tools-manifest.json describes every MCP tool the CLI exposes and is
consumed by ` + "`printing-press auth doctor`" + ` and ` + "`printing-press mcp-audit`" + `
without re-parsing the original spec.`,
	}
	cmd.AddCommand(newToolsManifestEmitCmd())
	return cmd
}

func newToolsManifestEmitCmd() *cobra.Command {
	var dir string
	var specPath string
	var asJSON bool
	var force bool

	cmd := &cobra.Command{
		Use:   "emit",
		Short: "Generate tools-manifest.json for a printed CLI from its spec",
		Long: `Generate (or regenerate) the tools-manifest.json file at the root of a
printed CLI directory. The file is derived from the CLI's archived spec
and the spec_format recorded in .printing-press.json. Supported spec
formats: openapi3, graphql, internal.

This is the recovery path for CLIs generated by older press versions
that didn't emit tools-manifest.json. Those CLIs are otherwise valid
but fail ` + "`printing-press publish validate`" + ` on the manifest check; running
emit unblocks them in place without re-running the full generate
pipeline. Idempotent: running it twice produces the same file unless
the source spec has changed.

When ` + "`--spec`" + ` is not supplied, the command looks for spec.yaml,
spec.yml, spec.json, schema.graphql, or schema.gql at the CLI root (in
that order — same set ` + "`printing-press mcp-sync`" + ` uses). When ` + "`--force`" + ` is
not supplied and tools-manifest.json already exists, the command
returns an error to avoid silently clobbering a hand-edited file.`,
		Example: `  printing-press tools-manifest emit --dir ~/printing-press/library/google-ads
  printing-press tools-manifest emit --dir ./google-ads --force --json
  printing-press tools-manifest emit --dir ./notion --spec ./openapi.json`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if dir == "" {
				return &ExitError{Code: ExitInputError, Err: fmt.Errorf("--dir is required")}
			}
			absDir, err := filepath.Abs(dir)
			if err != nil {
				return fmt.Errorf("resolving --dir: %w", err)
			}
			info, statErr := os.Stat(absDir)
			if statErr != nil || !info.IsDir() {
				return &ExitError{Code: ExitInputError, Err: fmt.Errorf("%s is not a directory", absDir)}
			}

			manifest, err := pipeline.ReadCLIManifest(absDir)
			if err != nil {
				return &ExitError{
					Code: ExitInputError,
					Err:  fmt.Errorf("reading .printing-press.json (this directory may not be a printed CLI): %w", err),
				}
			}
			if manifest.SpecFormat == "" {
				return &ExitError{
					Code: ExitInputError,
					Err:  fmt.Errorf(".printing-press.json missing spec_format; cannot select a parser"),
				}
			}
			// CLIs generated from documentation URLs (--docs) have no
			// structured spec to re-parse. Surface that explicitly
			// rather than letting the user hit a misleading
			// "unsupported spec_format" error.
			if manifest.SpecFormat == "docs" {
				return &ExitError{
					Code: ExitInputError,
					Err: fmt.Errorf("this CLI was generated from a documentation URL (--docs), " +
						"not a structured spec; tools-manifest cannot be derived. Regenerate " +
						"with `printing-press generate --spec <openapi-or-graphql-spec>` instead"),
				}
			}

			outPath := filepath.Join(absDir, pipeline.ToolsManifestFilename)
			if !force {
				if info, err := os.Stat(outPath); err == nil && !info.IsDir() {
					return &ExitError{
						Code: ExitInputError,
						Err:  fmt.Errorf("%s already exists; pass --force to overwrite", pipeline.ToolsManifestFilename),
					}
				}
			}

			resolvedSpec, data, err := resolveSpecForEmit(absDir, specPath)
			if err != nil {
				return &ExitError{Code: ExitInputError, Err: err}
			}

			parsed, err := parseSpecForEmit(manifest.SpecFormat, data, resolvedSpec)
			if err != nil {
				return fmt.Errorf("parsing spec (%s): %w", manifest.SpecFormat, err)
			}

			if err := pipeline.WriteToolsManifest(absDir, parsed); err != nil {
				return fmt.Errorf("writing %s: %w", pipeline.ToolsManifestFilename, err)
			}

			if asJSON {
				out := map[string]any{
					"passed":      true,
					"dir":         absDir,
					"spec":        resolvedSpec,
					"spec_format": manifest.SpecFormat,
					"output":      outPath,
					"resources":   len(parsed.Resources),
				}
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(out)
			}

			fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", outPath)
			return nil
		},
	}

	cmd.Flags().StringVar(&dir, "dir", "", "CLI directory containing .printing-press.json and an archived spec (required)")
	cmd.Flags().StringVar(&specPath, "spec", "", "Path to spec file (defaults to the first existing archived spec in <dir>)")
	cmd.Flags().BoolVar(&asJSON, "json", false, "Emit machine-readable JSON output")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite an existing tools-manifest.json")
	_ = cmd.MarkFlagRequired("dir")

	return cmd
}

// resolveSpecForEmit returns the spec path and its bytes. When explicit
// is set, that file is required to exist. Otherwise the function tries
// each archivedSpecCandidates filename in order and returns the first
// readable one.
func resolveSpecForEmit(dir, explicit string) (string, []byte, error) {
	if explicit != "" {
		abs, err := filepath.Abs(explicit)
		if err != nil {
			return "", nil, fmt.Errorf("resolving --spec: %w", err)
		}
		data, err := os.ReadFile(abs)
		if err != nil {
			return "", nil, fmt.Errorf("reading --spec %s: %w", abs, err)
		}
		return abs, data, nil
	}
	for _, name := range archivedSpecCandidates {
		path := filepath.Join(dir, name)
		data, err := os.ReadFile(path)
		if err == nil {
			return path, data, nil
		}
		if !errors.Is(err, os.ErrNotExist) {
			return "", nil, fmt.Errorf("reading %s: %w", path, err)
		}
	}
	return "", nil, fmt.Errorf(
		"no archived spec found in %s (looked for %v); pass --spec to point at one",
		dir, archivedSpecCandidates,
	)
}

// parseSpecForEmit parses spec bytes using the parser matching format.
// OpenAPI uses the lenient parser to match mcpsync — broken $refs in a
// spec that already produced runnable code should not block re-deriving
// a manifest from it.
func parseSpecForEmit(format string, data []byte, path string) (*spec.APISpec, error) {
	switch format {
	case "openapi3":
		return openapi.ParseWithPathLenient(data, path)
	case "graphql":
		return graphql.ParseSDLBytes(path, data)
	case "internal":
		return spec.ParseBytes(data)
	default:
		return nil, &ExitError{
			Code: ExitInputError,
			Err:  fmt.Errorf("unsupported spec_format %q (want openapi3, graphql, or internal)", format),
		}
	}
}
