// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
)

// mcpEndpointPath is the single path every tool call POSTs to. The upstream
// API is an MCP server, so there is one HTTP route and the tool name travels
// in the JSON-RPC envelope rather than the URL.
const mcpEndpointPath = "/v1/tools/mcp"

// mcpProtocolVersion is the MCP revision this client negotiates. Servers that
// speak a different revision answer initialize with their own; we accept it
// rather than failing, since tools/call is stable across revisions.
const mcpProtocolVersion = "2025-06-18"

// mcpRequest is a JSON-RPC 2.0 request. MCP carries every operation this way.
type mcpRequest struct {
	JSONRPC string `json:"jsonrpc"`
	ID      int64  `json:"id"`
	Method  string `json:"method"`
	Params  any    `json:"params,omitempty"`
}

// mcpResponse is a JSON-RPC 2.0 response envelope.
type mcpResponse struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      int64           `json:"id"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   *mcpErrorBody   `json:"error,omitempty"`
}

type mcpErrorBody struct {
	Code    int             `json:"code"`
	Message string          `json:"message"`
	Data    json.RawMessage `json:"data,omitempty"`
}

// MCPProtocolError is a JSON-RPC level failure: the server understood the
// transport but rejected the call (unknown tool, bad arguments, auth).
type MCPProtocolError struct {
	Code    int
	Message string
	Data    string
}

func (e *MCPProtocolError) Error() string {
	if e.Data != "" {
		return fmt.Sprintf("mcp error %d: %s (%s)", e.Code, e.Message, e.Data)
	}
	return fmt.Sprintf("mcp error %d: %s", e.Code, e.Message)
}

// MCPToolError is a tool-level failure: the call reached the tool and the tool
// reported isError. Kept distinct from MCPProtocolError because a tool error
// is a domain outcome (a validation failure the user can fix by changing
// flags), not a transport or contract problem.
type MCPToolError struct {
	Tool    string
	Message string
}

func (e *MCPToolError) Error() string {
	return fmt.Sprintf("%s: %s", e.Tool, e.Message)
}

// mcpToolResult is the tools/call result shape.
type mcpToolResult struct {
	Content           []mcpContent    `json:"content"`
	StructuredContent json.RawMessage `json:"structuredContent,omitempty"`
	IsError           bool            `json:"isError,omitempty"`
}

type mcpContent struct {
	Type string `json:"type"`
	Text string `json:"text,omitempty"`
}

// mcpRequestID hands out monotonically increasing JSON-RPC request IDs.
var mcpRequestID atomic.Int64

// mcpSession holds the negotiated session for streamable-HTTP servers.
//
// It is package-level rather than a Client field because Client is emitted by
// the shared client template and cannot grow per-transport fields. A printed
// CLI runs one process per invocation against one server, so a single session
// is the correct scope.
var mcpSession struct {
	sync.Mutex
	id          string
	initialized bool
}

// mcpBaseHeaders are required on every MCP HTTP request. Streamable HTTP
// servers may answer with either JSON or an SSE stream, so both are accepted
// and the response unwrapper handles each.
func mcpBaseHeaders() map[string]string {
	h := map[string]string{
		"Accept":               "application/json, text/event-stream",
		"MCP-Protocol-Version": mcpProtocolVersion,
	}
	mcpSession.Lock()
	if mcpSession.id != "" {
		h["Mcp-Session-Id"] = mcpSession.id
	}
	mcpSession.Unlock()
	return h
}

// ensureMCPSession performs the initialize handshake once per process.
//
// Stateless MCP servers accept tools/call directly, so a failed initialize is
// not fatal: we mark the session initialized and let the tool call surface any
// real error. Failing here would turn a working stateless server into a dead
// CLI.
func (c *Client) ensureMCPSession(ctx context.Context) {
	mcpSession.Lock()
	if mcpSession.initialized {
		mcpSession.Unlock()
		return
	}
	mcpSession.initialized = true
	mcpSession.Unlock()

	req := mcpRequest{
		JSONRPC: "2.0",
		ID:      mcpRequestID.Add(1),
		Method:  "initialize",
		Params: map[string]any{
			"protocolVersion": mcpProtocolVersion,
			"capabilities":    map[string]any{},
			"clientInfo": map[string]any{
				"name":    "mcp-intake-golden-pp-cli",
				"version": "1.0.0",
			},
		},
	}
	// Initialize is a read: it must not trip the verify-mode mutation gate.
	raw, _, err := c.PostQueryWithParamsAndHeaders(ctx, mcpEndpointPath, nil, req, mcpBaseHeaders())
	if err != nil {
		return
	}
	// A server that returns a session id expects it echoed on later calls.
	// The id travels in the Mcp-Session-Id response header, which the shared
	// transport does not surface, so fall back to the body's sessionId when
	// the server includes one there.
	if resp, decodeErr := decodeMCPEnvelope(raw); decodeErr == nil && resp.Result != nil {
		var init struct {
			SessionID string `json:"sessionId"`
		}
		if json.Unmarshal(resp.Result, &init) == nil && init.SessionID != "" {
			mcpSession.Lock()
			mcpSession.id = init.SessionID
			mcpSession.Unlock()
		}
	}
}

// mcpToolByPath maps each endpoint's synthetic path to the MCP tool it
// addresses. Generated commands, sync, and orchestration all build the
// synthetic path; the transport resolves it here so exactly one place knows
// how to speak JSON-RPC.
var mcpToolByPath = map[string]string{
	"/v1/tools/mcp/send_digest":        "send_digest",
	"/v1/tools/mcp/acme_create_widget": "acme_create_widget",
	"/v1/tools/mcp/delete_widget":      "delete_widget",
	"/v1/tools/mcp/get_widget":         "get_widget",
	"/v1/tools/mcp/widgets_list":       "widgets_list",
	"/v1/tools/mcp/update_widget":      "update_widget",
}

// mcpToolForPath resolves a request path to its MCP tool.
func mcpToolForPath(path string) (string, bool) {
	tool, ok := mcpToolByPath[path]
	return tool, ok
}

// mcpDispatch rewrites an ordinary request into a JSON-RPC tools/call POST.
//
// semanticMethod is the endpoint's declared verb (GET for a read, DELETE for a
// destructive tool). It is what decides whether the verify-mode mutation gate
// applies — the wire verb is always POST, so gating on the wire verb would
// short-circuit every read.
func (c *Client) mcpDispatch(ctx context.Context, tool, semanticMethod string, params map[string]string, body any, headerOverrides map[string]string, callerReadOnly bool) (json.RawMessage, int, error) {
	c.ensureMCPSession(ctx)

	req := mcpRequest{
		JSONRPC: "2.0",
		ID:      mcpRequestID.Add(1),
		Method:  "tools/call",
		Params: map[string]any{
			"name":      tool,
			"arguments": mcpArguments(params, body),
		},
	}

	readOnly := callerReadOnly || !isMutatingVerb(semanticMethod)
	raw, status, err := c.doInternal(ctx, "POST", mcpEndpointPath, nil, req, mcpMergeHeaders(headerOverrides), readOnly)
	if err != nil {
		return raw, status, err
	}
	unwrapped, err := unwrapMCPToolResult(tool, raw)
	if err != nil {
		return nil, status, err
	}
	return unwrapped, status, nil
}

// mcpArguments folds a request's query params and body into the single
// arguments object a tools/call takes. Reads arrive as params (so they route
// through the read transport) and writes as a body; both are tool arguments.
func mcpArguments(params map[string]string, body any) map[string]any {
	args := map[string]any{}
	for k, v := range params {
		args[k] = v
	}
	switch typed := body.(type) {
	case nil:
	case map[string]any:
		for k, v := range typed {
			args[k] = v
		}
	default:
		// Typed request structs round-trip through JSON so field names match
		// the tool schema rather than Go identifiers.
		if encoded, err := json.Marshal(body); err == nil {
			var fields map[string]any
			if json.Unmarshal(encoded, &fields) == nil {
				for k, v := range fields {
					args[k] = v
				}
			}
		}
	}
	return args
}

// mcpMergeHeaders overlays caller header overrides on the MCP base headers.
func mcpMergeHeaders(overrides map[string]string) map[string]string {
	h := mcpBaseHeaders()
	for k, v := range overrides {
		h[k] = v
	}
	return h
}

// QueryTool invokes a read-only MCP tool directly by name, for hand-written
// novel commands that compose tools the generated endpoints don't cover.
func (c *Client) QueryTool(ctx context.Context, tool string, args map[string]any) (json.RawMessage, error) {
	return c.callToolByName(ctx, tool, args, true)
}

// CallTool invokes a mutating MCP tool by name through the gated transport.
func (c *Client) CallTool(ctx context.Context, tool string, args map[string]any) (json.RawMessage, error) {
	return c.callToolByName(ctx, tool, args, false)
}

func (c *Client) callToolByName(ctx context.Context, tool string, args map[string]any, readOnly bool) (json.RawMessage, error) {
	if strings.TrimSpace(tool) == "" {
		return nil, fmt.Errorf("mcp tool name is empty")
	}
	semantic := "POST"
	if readOnly {
		semantic = "GET"
	}
	var body any
	if args != nil {
		body = args
	}
	data, _, err := c.mcpDispatch(ctx, tool, semantic, nil, body, nil, readOnly)
	return data, err
}

// unwrapMCPToolResult turns a tools/call response into the payload a generated
// command renders.
func unwrapMCPToolResult(tool string, raw json.RawMessage) (json.RawMessage, error) {
	// Under PRINTING_PRESS_VERIFY=1 the mutation gate returns a synthetic
	// envelope that is not a JSON-RPC response. Pass it through untouched so
	// the verifier sees the noop it expects.
	if isVerifyNoopEnvelope(raw) {
		return raw, nil
	}

	resp, err := decodeMCPEnvelope(raw)
	if err != nil {
		return nil, err
	}
	if resp.Error != nil {
		return nil, &MCPProtocolError{
			Code:    resp.Error.Code,
			Message: resp.Error.Message,
			Data:    strings.TrimSpace(string(resp.Error.Data)),
		}
	}
	if len(resp.Result) == 0 {
		return nil, fmt.Errorf("%s: server returned no result", tool)
	}

	var res mcpToolResult
	if err := json.Unmarshal(resp.Result, &res); err != nil {
		// Not the tools/call shape — hand back the raw result rather than
		// failing a call the server considered successful.
		return resp.Result, nil
	}
	if res.IsError {
		return nil, &MCPToolError{Tool: tool, Message: mcpContentText(res.Content)}
	}
	// structuredContent is the machine-readable payload when present.
	if len(res.StructuredContent) > 0 {
		return res.StructuredContent, nil
	}
	// Most servers return their payload as JSON inside a single text block.
	if text := mcpContentText(res.Content); text != "" {
		if trimmed := strings.TrimSpace(text); json.Valid([]byte(trimmed)) &&
			(strings.HasPrefix(trimmed, "{") || strings.HasPrefix(trimmed, "[")) {
			return json.RawMessage(trimmed), nil
		}
		wrapped, err := json.Marshal(map[string]string{"text": text})
		if err != nil {
			return nil, fmt.Errorf("%s: encoding text result: %w", tool, err)
		}
		return wrapped, nil
	}
	return resp.Result, nil
}

// isVerifyNoopEnvelope reports whether raw is the transport's synthetic
// verify-mode response rather than a server reply. The marker must match
// verifyShortCircuitEnvelope in client.go: mistaking the noop for a real
// reply surfaces a bogus "server returned no result" instead of the noop the
// verifier expects.
func isVerifyNoopEnvelope(raw json.RawMessage) bool {
	var probe struct {
		Synthetic *bool `json:"__pp_verify_synthetic__"`
	}
	if err := json.Unmarshal(raw, &probe); err != nil {
		return false
	}
	return probe.Synthetic != nil && *probe.Synthetic
}

// decodeMCPEnvelope parses a JSON-RPC response, unwrapping an SSE frame first
// when the server answered on the streamable-HTTP event channel.
func decodeMCPEnvelope(raw json.RawMessage) (*mcpResponse, error) {
	body := extractSSEData(raw)
	var resp mcpResponse
	if err := json.Unmarshal(body, &resp); err != nil {
		return nil, fmt.Errorf("decoding mcp response: %w", err)
	}
	return &resp, nil
}

// extractSSEData pulls the JSON payload out of an SSE frame. A streamable-HTTP
// MCP server may answer a single JSON-RPC call as one `data:` event instead of
// a bare JSON body. Input that is already JSON passes through unchanged.
func extractSSEData(raw []byte) []byte {
	trimmed := strings.TrimSpace(string(raw))
	if trimmed == "" || strings.HasPrefix(trimmed, "{") || strings.HasPrefix(trimmed, "[") {
		return raw
	}
	var out strings.Builder
	for _, line := range strings.Split(trimmed, "\n") {
		line = strings.TrimRight(line, "\r")
		if data, ok := strings.CutPrefix(line, "data:"); ok {
			out.WriteString(strings.TrimSpace(data))
		}
	}
	if out.Len() == 0 {
		return raw
	}
	return []byte(out.String())
}

// mcpContentText concatenates the text blocks of a content array.
func mcpContentText(content []mcpContent) string {
	parts := make([]string, 0, len(content))
	for _, c := range content {
		if c.Text != "" {
			parts = append(parts, c.Text)
		}
	}
	return strings.Join(parts, "\n")
}
