// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newRecordsListCmd(flags *rootFlags) *cobra.Command {
	var flagColumns string
	var flagFilterColumn string
	var flagFilterValue string
	var flagLimit int

	cmd := &cobra.Command{
		Use:         "list",
		Short:       "List stored records.",
		Example:     "  mcp-stdio-golden-pp-cli records list",
		Annotations: map[string]string{"pp:endpoint": "records.list", "pp:method": "GET", "pp:path": "/mcp/list_records", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "/mcp/list_records"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			if flagColumns != "" {
				path = appendArrayQueryParam(path, "columns", flagColumns, "form", true)
			}
			params := map[string]string{}
			if flagFilterColumn != "" {
				params["filter_column"] = formatCLIParamValue(flagFilterColumn)
			}
			if flagFilterValue != "" {
				params["filter_value"] = formatCLIParamValue(flagFilterValue)
			}
			if flagLimit != 0 {
				params["limit"] = formatCLIParamValue(flagLimit)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "records", true, path, params, nil, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Honor --limit when the API accepts but ignores ?limit=N.
			data = truncateJSONArray(data, flagLimit)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagColumns, "columns", "", "")
	cmd.Flags().StringVar(&flagFilterColumn, "filter-column", "", "")
	cmd.Flags().StringVar(&flagFilterValue, "filter-value", "", "")
	cmd.Flags().IntVar(&flagLimit, "limit", 100, "")

	return cmd
}
